apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-app
  namespace: students-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-app
  template:
    metadata:
      labels:
        app: students-app
    spec:
      containers:
        - name: students-app
          image: uxheri/students-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "UXHERI69"
          volumeMounts:
            - name: students-db-storage
              mountPath: /app/data
      volumes:
        - name: students-db-storage
          persistentVolumeClaim:
            claimName: students-db-pvc

