apiVersion: v1
kind: Service
metadata:
  name: students-app-service
  namespace: students-app
spec:
  type: ClusterIP
  selector:
    app: students-app
  ports:
    - port: 80
      targetPort: 5000

